// Code generated by mockery v1.1.2. DO NOT EDIT.

package gapictest

import (
	admin "github.com/animeapis/go-genproto/iam/admin/v1alpha1"

	iterator "google.golang.org/api/iterator"

	mock "github.com/stretchr/testify/mock"
)

// RoleIterator is an autogenerated mock type for the RoleIterator type
type RoleIterator struct {
	mock.Mock
}

// Next provides a mock function with given fields:
func (_m *RoleIterator) Next() (*admin.Role, error) {
	ret := _m.Called()

	var r0 *admin.Role
	if rf, ok := ret.Get(0).(func() *admin.Role); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*admin.Role)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// PageInfo provides a mock function with given fields:
func (_m *RoleIterator) PageInfo() *iterator.PageInfo {
	ret := _m.Called()

	var r0 *iterator.PageInfo
	if rf, ok := ret.Get(0).(func() *iterator.PageInfo); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*iterator.PageInfo)
		}
	}

	return r0
}
